### ISSUE TITLE
"always" Checkbox doesn't have an effect

### ISSUE THREAD

**Issue by commander-keen** [qwerty12/AlternateAppPicker#4]
I used to use this extension sucesfully on my Galaxy SIII with JellyBean (4.3) but on my S4 Kitkat (4.4.2) the dialog needs two klicks to open the target app 
AND
the "always" checkbox does not successfully make the system remember which app I chose. 
Instead, the next time the system will ask again which app to take.

**Comment by qwerty12** [comment]
I haven't touched this in a long time. I suggest taking a look at the
Complete Action Plus module.

**Comment by commander-keen** [comment]
Okay, using that one then. Thanks.
Maybe this module is obsolete then...

**Comment by IzzySoft** [comment]
*Complete Action Plus" didn't work for me at all (claims not being activated or reboot missing, though I've booted a couple of times already after activating it). Will give yours a try next, as I'm still on JB with the device-in-question.

However, @commander-keen : Please note that there's another module specifically for KK: [Alternate App Picker (KK)](http://repo.xposed.info/module/com.iagucool.alternateapppicker) – just in case you have the same trouble with CAP as I have :stuck_out_tongue_winking_eye:

**Comment by commander-keen** [comment]
Unfortunately I'm on Android 5 on a Galaxy S4 now where the Xposed framework has never become available for. Anyway, thanks for the hint.

**Comment by IzzySoft** [comment]
@commander-keen you mean Xposed is not available for Lollipop (which isn't quite true: it is avalable for 5.0 and even 5.1 meanwhile) – or just not for the S4 (which I can't tell why it should be an exception)? Anyway: In case you need it again, you at least have some alternatives to chose from :stuck_out_tongue_winking_eye:

**Comment by commander-keen** [comment]
I'm refering to Samsung based ROMs (hence Galaxy S4), which it is not available for alltogether, at least afaik.

**Comment by IzzySoft** [comment]
Ah – OK, thanks for that detail! Wasn't aware of it. I only rawly remember something about issues with the new TouchWiz, so probably it's still that. Sad. Hopefully solved soon, fingers crossed!
